# Generated by Django 5.1.6 on 2025-03-01 13:28

from django.db import migrations

def add_choices_to_question2(apps, schema_editor):
    Choice = apps.get_model("polls", "Choice")
    Question = apps.get_model("polls", "Question")

    try: 
        question = Question.objects.get(pk=2)

        Choice.objects.create(
            question=question,
            choice_text="Blue",
            votes=0,
        )
        Choice.objects.create(
            question=question,
            choice_text="Red",
            votes=0,
        )
        Choice.objects.create(
            question=question,
            choice_text="Green",
            votes=0,
        )

        print(f"Choices added to question: {question.question_text}")
    except Question.DoesNotExist:
            print("Question does not exist")
        
def remove_choices(apps, schema_editor):
    # Pour annuler la migration si nécessaire
    Choice = apps.get_model('polls', 'Choice')
    Question = apps.get_model('polls', 'Question')
    
    try:
        question = Question.objects.get(pk=2)
        Choice.objects.filter(question=question).delete()
    except Question.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(add_choices_to_question2, remove_choices),
    ]
